version: '3.8'

services:
  back:
    build:
      context: ./back-service
      platforms:
        - linux/amd64
        - linux/arm64
    image: saurabhjha1/simple-us-app-back:latest
    ports:
      - "8080"
    networks:
      - custom_network
    environment:
      - OTEL_SERVICE_NAME=back-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    command: ["opentelemetry-instrument", "--log_level", "debug", "python", "app.py"]

  front:
    build:
      context: ./front-service
      platforms:
        - linux/amd64
        - linux/arm64
    image: saurabhjha1/simple-us-app-front:latest
    depends_on:
      - back
    ports:
      - "8080:8080"  # Expose to the host
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '0.1'  # 100m
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 100M
    environment:
      - OTEL_SERVICE_NAME=front-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    command: ["opentelemetry-instrument", "--log_level", "debug", "python", "app.py"]

  loadgen:
    build:
      context: ./loadgen-service
      platforms:
        - linux/amd64
        - linux/arm64
    image: saurabhjha1/simple-us-app-loadgen:latest
    depends_on:
      - front
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 100M

networks:
  custom_network:
