apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: simple-us
spec:
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
