apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: simple-us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      initContainers:
        - name: check-back-service
          image: busybox
          command:
          - sh
          - -c
          - "until wget -q -O - http://back-service:80/ > /dev/null; do echo 'Waiting for back-service'; sleep 5; done" 
      containers:
      - name: front
        image: {{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}
        env:
        - name: SINGLE_US
          value: {{ .Values.front.env.SINGLE_US | quote }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: {{ .Values.front.resources.limits.cpu | quote }}
            memory: {{ .Values.front.resources.limits.memory | quote }}
          requests:
            cpu: {{ .Values.front.resources.requests.cpu | quote }}
            memory: {{ .Values.front.resources.requests.memory | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
