apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rate-limiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rate-limiter
  template:
    metadata:
      labels:
        app: nginx-rate-limiter
    spec:
      initContainers:
        - name: check-back-service
          image: busybox
          command:
          - sh
          - -c
          - "until wget -q -O - http://front-service:80/ > /dev/null; do echo 'Waiting for back-service'; sleep 5; done" 
      containers:
      - name: nginx
        image: nginx:1.19
        resources:
          limits:
            cpu: {{ .Values.nginx.resources.limits.cpu | quote }}
            memory: {{ .Values.nginx.resources.limits.memory | quote }}
          requests:
            cpu: {{ .Values.nginx.resources.requests.cpu | quote }}
            memory: {{ .Values.nginx.resources.requests.memory | quote }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx-rate-limit.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
